language: 
    - python
python:
    - "3.6"
sudo: 
    - required
# command to install dependencies
install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda config --add channels r
    - conda config --add channels bioconda

    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION  
        pandas biopython cython numpy networkx seaborn pyBigwig six pysam ujson 
        hisat2 bowtie2=2.2.5 bedtools samtools snakemake bedtools atropos seqkit
        xopen ucsc-gtftogenepred ucsc-genePredToBed bedops xopen
    - source activate test-environment
    - pip install .
    - git clone https://github.com/wckdouglas/sequencing_tools.git
    - cd sequencing_tools
    - pip install -r requirements.txt 
    - pip install .
    - cd ../


# test
script:
    - bash test_script.sh

