tgirt_count.py map \
    -1 test_map/test.1.fq.gz \
    -2 test_map/test.2.fq.gz \
    --outdir test_map/test_result \
    --samplename test --univec UniVec_Core \
    --hisat_index hg19_genome --bowtie2_index hg19_genome \
    --bedpath genes --splicesite splicesites.tsv \
    --rRNA_mt_index rRNA_mt --smRNA_index smallRNA -p 24 \
    --trim_aggressive --repeats rmsk.bed.gz --umi 6 \
    --repeats_index all_rmsk_From_bed \
    --snakemake --dry 
